export type Variables =
  | 'accent'
  | 'background'
  | 'foreground'
  | 'block'
  | 'message-box'
  | 'mention'
  | 'success'
  | 'warning'
  | 'error'
  | 'hover'
  | 'scrollbar-thumb'
  | 'scrollbar-track'
  | 'primary-background'
  | 'primary-header'
  | 'secondary-background'
  | 'secondary-foreground'
  | 'secondary-header'
  | 'tertiary-background'
  | 'tertiary-foreground'
  | 'status-online'
  | 'status-away'
  | 'status-busy'
  | 'status-streaming'
  | 'status-invisible'

// While this isn't used, it'd be good to keep this up to date as a reference or for future use
export type HiddenVariables = 'font' | 'ligatures' | 'app-height' | 'sidebar-active' | 'monospace-font'

export type Fonts =
  | 'Open Sans'
  | 'Inter'
  | 'Atkinson Hyperlegible'
  | 'Roboto'
  | 'Noto Sans'
  | 'Lato'
  | 'Bree Serif'
  | 'Montserrat'
  | 'Poppins'
  | 'Raleway'
  | 'Ubuntu'
  | 'Comic Neue'
export type MonospaceFonts = 'Fira Code' | 'Roboto Mono' | 'Source Code Pro' | 'Space Mono' | 'Ubuntu Mono' | 'JetBrains Mono'
